USE $MAIN$;

-- update communities and roles ... \
SET @role_id = (SELECT id FROM role WHERE identifier='enduser');
UPDATE domain SET identifier='wois', name='WOIS', description='The Water Observation and Information System (WOIS) is an open source software tool for monitoring developed by DEIMOS, assessing and inventorying water resources in a cost-effective manner using Earth Observation data. The output workflows and products available within the platform are the following: large lakes water quality monitoring, land degradation index, land cover and land use mapping, land cover change detection, small water body mapping, flood mapping system, hydrological characterization, water supply and sanitation planning support, seasonal variation of wetland areas and the erosion potential indicator.', icon_url='https://store.terradue.com/api/hydro-smhi-apps/images/wois.png', discuss='hydro/co-wois' WHERE identifier='hydro-DEIMOS';
SET @domain_id = (SELECT id FROM domain WHERE identifier='wois');
INSERT IGNORE INTO rolegrant (id_usr,id_role,id_domain) SELECT u.id,@role_id,@domain_id FROM usr as u WHERE u.level = 2 OR u.level = 3 ;

UPDATE domain SET identifier='floodmonitoring', name='Flood Monitoring', description='The Flood Monitoring Service developed by TRE-Altamira enables the detection and extent analysis of large extent floods at high resolution using Sentinel-1 and historical Envisat SAR data as well as the possibility of results refinement using Sentinel-2 Optical Data. Additionally the service includes statistics to assess the evolution of water extent and floods over time from basic statistics (flood and water frequency maps, maximum floodable area and time series of floods) and advanced temporal statistics to analyze trends.', icon_url='https://store.terradue.com/api/hydro-smhi-apps/images/fm.png', discuss='hydro/co-floodmonitoring' WHERE identifier='hydro-ALTAMIRA';
SET @domain_id = (SELECT id FROM domain WHERE identifier='floodmonitoring');
INSERT IGNORE INTO rolegrant (id_usr,id_role,id_domain) SELECT u.id,@role_id,@domain_id FROM usr as u WHERE u.level = 2 OR u.level = 3 ;

UPDATE domain SET identifier='hydrologicalmodelling', name='Hydrological Modelling', description='The Hydrological Modelling Service developed by SMHI provides data on river discharge, lake Outflow, lakes and rivers water level, as well as land surface water balance components (precipitation, evapotranspiration, soil moisture) within an area covered by the model domain (e.g. NigerHYPE model application covering the Niger river basin). The service provides to users the possibility to upload their own hydrological model and/or their own input data to existing or new models, as well as the assimilation of Earth Observation output data from the other TEP Hydrology processing services.', icon_url='https://store.terradue.com/api/hydro-smhi-apps/images/hm.png', discuss='hydro/co-hydrological-modelling' WHERE identifier='hydro-SMHI';
SET @domain_id = (SELECT id FROM domain WHERE identifier='hydrologicalmodelling');
INSERT IGNORE INTO rolegrant (id_usr,id_role,id_domain) SELECT u.id,@role_id,@domain_id FROM usr as u WHERE u.level = 2 OR u.level = 3 ;

INSERT INTO domain (identifier, name, description, kind, icon_url, discuss) VALUES ('waterquality','Water Quality','The Water Quality Service carried out by EOMAP provides key parameters of water quality measures such as chlorophyll-a, total suspended solids and colored dissolved organic matter based on organic absorption and surface water temperature. The service is generated by EOMAPs proprietary water quality processor Modular Inversion and Processing System (MIP). The processors include sensor independent state of the art algorithms including adjacency correction, coupled atmospheric in water retrieval considering all bidirectional aspects from extreme clean to extreme turbid case 2 waters in a physically correct approach.',4,'http://www.eomap.com/wp-content/uploads/2016/01/20160120_mississippi_1.1-710x505.png', 'hydro/co-water-quality');
SET @domain_id = (SELECT LAST_INSERT_ID());
INSERT IGNORE INTO rolegrant (id_usr,id_role,id_domain) SELECT u.id,@role_id,@domain_id FROM usr as u WHERE u.level = 2 OR u.level = 3 ;

INSERT INTO domain (identifier, name, description, kind, icon_url, discuss) VALUES ('waterlevel','Water Level','The Water Level Service has been deployed by IsardSAT and provides water level time series referenced to geoid for lakes, rivers and reservoirs from Sentinel-3 and CrySAT-2 altimeters. Radar altimeters are active sensors that use the ranging capability of radar to measure the surface height profile along the satellite track.',4,'https://www.isa.org/uploadedImages/Content/Standards_and_Publications/ISA_Publications/InTech_Magazine/2010/August/2010_7-8_36-home.jpg','hydro/co-water-level');
SET @domain_id = (SELECT LAST_INSERT_ID());
INSERT IGNORE INTO rolegrant (id_usr,id_role,id_domain) SELECT u.id,@role_id,@domain_id FROM usr as u WHERE u.level = 2 OR u.level = 3 ;

INSERT INTO domain (identifier, name, description, kind, icon_url, discuss) VALUES ('smallwaterbody','Small Water Body Mapping','The Small Water Body Mapping Service developed by TRE-Altamira provides the extent and temporal evolution of permanent and non-permanent water bodies providing it into detailed mapping, Time Series and other statistical information. The service is based on Sentinel 1 SAR acquisitions and ASAR for historical analysis.',4,'https://store.terradue.com/api/hydro-smhi-apps/images/hm.png','hydro/co-small-water-body');
SET @domain_id = (SELECT LAST_INSERT_ID());
INSERT IGNORE INTO rolegrant (id_usr,id_role,id_domain) SELECT u.id,@role_id,@domain_id FROM usr as u WHERE u.level = 2 OR u.level = 3 ;

INSERT INTO domain (identifier, name, description, kind, icon_url, discuss) VALUES ('nigerriver', 'Niger River', '', 3, '', 'hydro/co-niger-river');
INSERT INTO domain (identifier, name, description, kind, icon_url, discuss) VALUES ('redriver', 'Red River', '', 3, '', 'hydro/co-red-river');
INSERT INTO domain (identifier, name, description, kind, icon_url, discuss) VALUES ('tiger', 'Tiger', '', 3, '', 'hydro/co-tiger');

SET @role_id = (SELECT id FROM role WHERE identifier='starter');
DELETE FROM rolegrant WHERE id_role=@role_id;
SET @role_id = (SELECT id FROM role WHERE identifier='explorer');
DELETE FROM rolegrant WHERE id_role=@role_id;
-- RESULT

-- update services ...\
UPDATE service SET tags='floodmonitoring', icon_url='https://store.terradue.com/hydro-smhi-apps/images/fm.png' WHERE identifier IN ('17af570f-8992-4a42-a210-7df2faca8906','e5896b32-924e-424e-9217-1b8925fd51fa');
UPDATE service SET tags='wois', icon_url='https://store.terradue.com/hydro-smhi-apps/images/wois.png' WHERE identifier IN ('94d3b50c-36c7-4ab0-b184-80405734f22e');
UPDATE service SET tags='hydrologicalmodelling', icon_url='https://store.terradue.com/hydro-smhi-apps/images/hm.png' WHERE identifier IN ('3bbe0182-bc2a-4fab-b4f6-e8860f2ff9f5');
SET @domain_id = (SELECT id FROM domain WHERE identifier='waterquality');
UPDATE service SET domain_id=@domain_id, tags='waterquality', icon_url='https://store.terradue.com/hydro-smhi-apps/images/wq.png' WHERE identifier IN ('8ea494b2-f5c0-4602-b16d-be06499aee9e');
SET @domain_id = (SELECT id FROM domain WHERE identifier='waterlevel');
UPDATE service SET domain_id=@domain_id, tags='waterlevel', icon_url='https://store.terradue.com/hydro-smhi-apps/images/wl.png' WHERE identifier IN ('71cb3cb1-ecb3-44c1-944e-334d9f94f2b6');

-- RESULT


